### ISSUE TITLE
Build Error: No such file or directory  #include<.../voro++.hh>

### ISSUE THREAD

**Issue by sjl767** [woodem/woo#16]
Attempting to build with the command `python setup.py --command-packages=stdeb.command bdist_deb` returns an error that one of the header files aren't found. More specifically:

    In file included from build-src-tree/src/chunk-01.cpp:7:0:
    build-src-tree/../py/_triangulated.cpp:12:35: fatal error: woo/lib/voro++/voro++.hh: No such file or directory
    #include<woo/lib/voro++/voro++.hh>

The git revision used is f0f1a01.

**Comment by eudoxos** [comment]
Alright, all clear. That's an issue with setup.py, using scons for buildling is without this issue.

**Comment by eudoxos** [comment]
Thanks for spotting that. If you are developping on Debian/Ubuntu, compilation with scons is much more flexible (it will rebuild only what is necessary when you update somce code).
