### ISSUE TITLE
Clean up merged buoyancy code

### ISSUE THREAD

**Issue by eudoxos** [woodem/woo#19]
pull request #18 merged basis for buoyancy and drag force, but it is not functional. Discuss changes here.

**Comment by eudoxos** [comment]
I did some cleanup of the code in https://github.com/woodem/woo/commit/06afc17f13135f9ba6ab3fb210a3def0dc21b37d but there are some unresolved issues (marked with `XXX`). I removed node (it is useless if we use gravity as defined by DemField) and used `surfPt` for determining liquid level, plus removed a lot of code which was not needed. Please go through it, check if things are correct (depth computation etc). If you want to fork again and then do a pul lrequest, go ahead and do it.

**Comment by sjl767** [comment]
Hey, I commented on the code marked with `XXX` last. I've been trying to find papers/references for equations connecting drag forces with liquid depth on the side. So far, no luck on that. What do you think of [this](http://www.civil.uwaterloo.ca/enve214/files/reynolds_number_and_drag.pdf) (look at Page 6's equation). 

Also I guess there is still the problem where the gravity engine is taking precedence over the buoyancy engine? At least in my test simulation it appears that the buoyancy engine has no effect as long as gravity is non-zero.

**Comment by eudoxos** [comment]
Depends on how you order the engines. NewtonIntegrator will apply forces, reset them to zero and add gravity immediately, if applicable. It cannot really take precedence, those pieces fo the puzzle are designed to act incrementally so that new ones can be put in easily. Hard to tell without seeing how you ordered engines in the simulation. Script?

**Comment by sjl767** [comment]
Just a simple script where a cloud of spheres fall into a container:

'''import woo, woo.dem, woo.core, woo.pack, woo.log, woo.gl, math
from woo.core import *
from woo.dem import *
from minieigen import *
from woo import qt
from woo import gl
from woo import pack
import os.path, csv, math, os
import random

S=woo.master.scene=woo.core.Scene(fields=[DemField(gravity=(0,0,-9.81))],engines=DemField.minimalEngines(model=woo.models.ContactModelSelector(name='linear',damping=0.015)))

Ice=IceMat(young=(1e6),density=(905),tanPhi=(math.tan(math.radians(36))),ktDivKn=(1/2.66),breakN=(0.025),alpha=([.159155,.0795775]),beta=([1.2,0.282095,0.1410474]),mu=math.tan(math.radians(36)),id=1)

'''Particles'''
w2 = woo.utils.wall(position=(0,0,0),axis=2,mat=Ice)
w3 = woo.utils.wall(position=(0,0,0),axis=0,mat=Ice)
w4 = woo.utils.wall(position=(5,0,0),axis=0,mat=Ice)
w5 = woo.utils.wall(position=(0,0,0),axis=1,mat=Ice)
w6 = woo.utils.wall(position=(0,5,0),axis=1,mat=Ice)
box = (w2,w3,w4,w5,w6)

spheres = pack.SpherePack()
spheres.makeCloud((0,0,0),(5,5,4.9),rMean=0.1,periodic=False,num=5000)
spheres.toDem(S,S.dem,mat=Ice)

S.dem.par.add(box)

S.engines += [HalfspaceBuoyancy(liqRho=1000,waterHeight=5.0,dragCoef=0.14,drag=True)]
S.engines += [PyRunner(command='forceCheck()',stepPeriod=1)]

def forceCheck():
  randomcheck = random.randrange(0,len(S.dem.par))
  print (S.dem.par[randomcheck].f)
'''

**Comment by eudoxos** [comment]
Will check it later this week. Cheers.

**Comment by sjl767** [comment]
Hi @eudoxos , were you able to check the test? Just reminding in case you forgot haha

**Comment by eudoxos** [comment]
Hi,

not sure why you were checking force of a random particle?  I hope next time you can do this kind of debugging yourself ;) Always much better to test with one particle **only** so that you can compare with the analytical solution; also putting some cerr<<...<<endl traces to the the code temporarily helps a lot; with many particles, it is too messy.

it is fixed in https://github.com/woodem/woo/commit/3217e70d069cc84b18a944d75529f59a15df71d4 , and an examples script was added. This is plot from the example which shows that both drag and buoyancy have the effect they should. There was no other problem than sign of depth which was inversed.

Please test and close. Will be offline from next Wednesday for 2.5 months.

![buoyancy-with-drag](https://cloud.githubusercontent.com/assets/1029876/11271282/52ec4996-8ec5-11e5-9adb-20e86f13f9d3.png)

**Comment by sjl767** [comment]
Hello @eudoxos 

Unfortunately I haven't been able to fully test the buoyancy engine as I was caught up with other work. My work done here was a part of a work term for my degree and my current work term is coming to an end. That means that I won't be able to close this off with you. The next work term student will probably continue where I left off. I have left them all my work and a link back to this thread.

Thank you so much for the wonderful learning experience of my first foray into open source projects. Hope you had a good break (by the time you read this)! I will be checking in on the progress of this functionality whenever I can in my personal time.

**Comment by eudoxos** [comment]
Hi, good to hear from you. I also hope your colleague will continue :) Cheers, Václav
