### ISSUE TITLE
About Box Creation

### ISSUE THREAD

**Issue by MarcoTar** [woodem/woo#22]
Hi. Vaclav
Here's the code that I wrote and now I paste here in order to let you have a detailed view of it. 
__________________________________________________________________________
`from woo.core import *
from woo.dem import *
from woo.fem import *
import woo
import woo.gl
import math
from math import pi
from minieigen import *
import woo.pack, woo.utils, numpy
import math
woo.master.usesApi=10103
# create the scene
S=woo.master.scene=Scene(fields=[DemField(gravity=(0,0,-9.81))],dtSafety=.8)
# graphic library
S.gl=woo.gl.GlSetup(
    woo.gl.Gl1_Membrane(uScale=0,relPhi=0,refConf=False),
    woo.gl.Gl1_DemField(shape=woo.gl.Gl1_DemField.shapeNonSpheres,colorBy=woo.gl.Gl1_DemField.colorDisplacement,vecAxis='norm',colorBy2=woo.gl.Gl1_DemField.colorVel),
)
S.gl.demField.colorRange2.mnmx=(0,2.)
# create the membrane
xmax,ymax=3.4,3.4
xdiv,ydiv=35,35
mat_membrane=FrictMat(
            young=30e9,
            tanPhi=.3,
            ktDivKn=.25,
            density=2500
)
ff=woo.pack.gtsSurface2Facets(woo.pack.sweptPolylines2gtsSurface([[(x,y,0) for x in numpy.linspace(0,xmax,num=xdiv)] for y in numpy.linspace(0,ymax,num=ydiv)]),flex=True,halfThick=.01,mat=mat_membrane)
S.dem.par.add(ff,nodes=True)
# set boundary conditions and set some fake masses and inertia of mesh nodes
if 1:
for n in S.dem.nodes:
    n.dem.blocked=''
    #if n.pos[0]==0.3 and (n.pos[1]==0.3): n.dem.blocked='xyz'
    if (n.pos[0]>.25 and n.pos[0]<.35) and (n.pos[1]>.25 and n.pos[1]<.35): n.dem.blocked='xyz'
    if (n.pos[0]>.25 and n.pos[0]<.35) and (n.pos[1]>3.05 and n.pos[1]<3.15): n.dem.blocked='xyz'
    if (n.pos[0]>3.05 and n.pos[0]<3.15) and (n.pos[1]>.25 and n.pos[1]<.35): n.dem.blocked='xyz'
    if (n.pos[0]>3.05 and n.pos[0]<3.15) and (n.pos[1]>3.05 and n.pos[1]<3.15): n.dem.blocked='xyz'

if 0:
for n in S.dem.nodes:
    n.dem.blocked=''
    if n.pos[0]==0 and (n.pos[1]==0): n.dem.blocked='xyz'
    if n.pos[0]==3.4 and (n.pos[1]==0): n.dem.blocked='xyz'
    if n.pos[0]==0 and (n.pos[1]==3.4): n.dem.blocked='xyz'
    if n.pos[0]==3.4 and (n.pos[1]==3.4): n.dem.blocked='xyz'

# create the box
mat_wall=woo.dem.FrictMat(
                        density=2650,
                        young=200e6,
                        ktDivKn=0.25,
                        tanPhi=0.3
)
Box=woo.triangulated.box(
                        dim=(3.4,3.4,1), 
                        center=Vector3(1.7,1.7,0.5), 
                        which=Vector6i(1, 1, 0, 1, 1, 0), 
                        mat=mat_wall, 
                        wire=False,
                        color=0.7, 
                        halfThick=0.0,
                        fixed=True
)
S.lab.boxNode=Node(pos=(1.7,1.7,0.5),dem=ClumpData(blocked='xyzXYZ'))
S.dem.par.addClumped(Box,centralNode=S.lab.boxNode)
# create the grains
mat_grains=mat_wall
sp=woo.pack.SpherePack()
sp.makeCloud((0,0,0),(3.4,3.4,1),rMean=0.06,rRelFuzz=0.1,periodic=False,num=-1)
sp.toSimulation(S,mat=mat_grains)`
________________________________________________________________________
And let me have a description about the error which I found it here.
The first time you run this simulation in order to get the Scene, you will find this Error Warning displayed by Woo.
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/lib/python2.7/dist-packages/wooMain.pyc in <module>()
----> 1 Box=woo.triangulated.box(
      2                         dim=(3.4,3.4,1),
      3                         center=Vector3(1.7,1.7,0.5),
      4                         which=Vector6i(1, 1, 0, 1, 1, 0),
      5                         mat=mat_wall,

AttributeError: 'module' object has no attribute 'triangulated'
Woo [60]: S.lab.boxNode=Node(pos=(1.7,1.7,0.5),dem=ClumpData(blocked='xyzXYZ'))
Woo [61]: S.dem.par.addClumped(Box,centralNode=S.lab.boxNode)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/usr/lib/python2.7/dist-packages/wooMain.pyc in <module>()
----> 1 S.dem.par.addClumped(Box,centralNode=S.lab.boxNode)

NameError: name 'Box' is not defined
_______________________________________________________
Of course, if you open the 3D viewer, there is no the BOX which I created.
And if you clear the present Code and Paste the SAME code again, it doesn't show the error and the BOX will appear.
This is what I found during my simulation.
If you need more detailed information, contact me.
Regards 
Feixiang Xuan`

**Comment by eudoxos** [comment]
Hi, can you edit your first post so that all the code is together? Use the "code block" markup for that.

**Comment by MarcoTar** [comment]
`from woo.core import *
from woo.dem import *
from woo.fem import *
import woo
import woo.gl
import math
from math import pi
from minieigen import *
import woo.pack, woo.utils, numpy
import math
woo.master.usesApi=10103
S=woo.master.scene=Scene(fields=[DemField(gravity=(0,0,-9.81))],dtSafety=.8)
S.gl=woo.gl.GlSetup(
    woo.gl.Gl1_Membrane(uScale=0,relPhi=0,refConf=False),
    woo.gl.Gl1_DemField(shape=woo.gl.Gl1_DemField.shapeNonSpheres,colorBy=woo.gl.Gl1_DemField.colorDisplacement,vecAxis='norm',colorBy2=woo.gl.Gl1_DemField.colorVel),
)
S.gl.demField.colorRange2.mnmx=(0,2.)
xmax,ymax=3.4,3.4
xdiv,ydiv=35,35
mat_membrane=FrictMat(
            young=30e9,
            tanPhi=.3,
            ktDivKn=.25,
            density=2500
)
ff=woo.pack.gtsSurface2Facets(woo.pack.sweptPolylines2gtsSurface([[(x,y,0) for x in numpy.linspace(0,xmax,num=xdiv)] for y in numpy.linspace(0,ymax,num=ydiv)]),flex=True,halfThick=.01,mat=mat_membrane)
S.dem.par.add(ff,nodes=True)
if 1:
for n in S.dem.nodes:
    n.dem.blocked=''
    if (n.pos[0]>.25 and n.pos[0]<.35) and (n.pos[1]>.25 and n.pos[1]<.35): n.dem.blocked='xyz'
    if (n.pos[0]>.25 and n.pos[0]<.35) and (n.pos[1]>3.05 and n.pos[1]<3.15): n.dem.blocked='xyz'
    if (n.pos[0]>3.05 and n.pos[0]<3.15) and (n.pos[1]>.25 and n.pos[1]<.35): n.dem.blocked='xyz'
    if (n.pos[0]>3.05 and n.pos[0]<3.15) and (n.pos[1]>3.05 and n.pos[1]<3.15): n.dem.blocked='xyz'

if 0:
for n in S.dem.nodes:
    n.dem.blocked=''
    if n.pos[0]==0 and (n.pos[1]==0): n.dem.blocked='xyz'
    if n.pos[0]==3.4 and (n.pos[1]==0): n.dem.blocked='xyz'
    if n.pos[0]==0 and (n.pos[1]==3.4): n.dem.blocked='xyz'
    if n.pos[0]==3.4 and (n.pos[1]==3.4): n.dem.blocked='xyz'

mat_wall=woo.dem.FrictMat(
                        density=2650,
                        young=200e6,
                        ktDivKn=0.25,
                        tanPhi=0.3
)
Box=woo.triangulated.box(
                        dim=(3.4,3.4,1), 
                        center=Vector3(1.7,1.7,0.5), 
                        which=Vector6i(1, 1, 0, 1, 1, 0), 
                        mat=mat_wall, 
                        wire=False,
                        color=0.7, 
                        halfThick=0.0,
                        fixed=True
)
S.lab.boxNode=Node(pos=(1.7,1.7,0.5),dem=ClumpData(blocked='xyzXYZ'))
S.dem.par.addClumped(Box,centralNode=S.lab.boxNode)
mat_grains=mat_wall
sp=woo.pack.SpherePack()
sp.makeCloud((0,0,0),(3.4,3.4,1),rMean=0.06,rRelFuzz=0.1,periodic=False,num=-1)
sp.toSimulation(S,mat=mat_grains)`

**Comment by MarcoTar** [comment]
Hi Valclav.
It's my fault. Sorry to let you waste time on it.
I always use copy and paste to check the code. Since you told me use sth to open the code from the command-line, I just try it again. Everything works fine.
Sorry to let you waste time on it.
Thanks a lot.

**Comment by eudoxos** [comment]
Okay, closing. Reopen or open a new issue if there is a problem.
