### ISSUE TITLE
Installation fails on WSL1 Ubuntu 18.04 - Cmake Errors

### ISSUE THREAD

**Issue by zipmo** [woodem/woo#30]
Dear all,

I tried to install wooDEM on Windows 10 via WSL as described here: https://woodem.org/user/installation.html#windows

After installing the X server, I tried to run woo-install.py, which would give me two Cmake errors:

1) 
CMake Error at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1947 (message):
  Unable to find the requested Boost libraries.
  Boost version: 1.65.1
  Boost include path: /usr/include
  Could not find the following Boost libraries:
          boost_python36
  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost. 

2)
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GLEW (missing: GLEW_INCLUDE_DIR GLEW_LIBRARY)

I was, however, able to resolve the second error by manually installing the glew package. The boost package is also installed and fulfills the version requirements.

Any idea on this issue?

Thanks and best,
Sebastian

**Comment by eudoxos** [comment]
Hi, this is somewhat strange. The install script should install dependencies automatically, though I see now there is no mention of glew there. Good that you solved it. For boost, check if you have libbost-python-dev installed. If you don't succeed, please attach the full cmake log.

Anyway, I would recommend installing using Ubuntu 20.04 in WSL (1 or 2), unless you have a specific need for 18.04.

**Comment by zipmo** [comment]
Thanks for the reply, @eudoxos! As the setup instructions recommend Ubuntu 18.04, I used that in the first place.

I tried with Ubuntu 20.04 today and indeed this circumvents the boost problem, but gives an error on OpenGL. I'm attaching the bash output (starting after the packages have been installed) in a separate file - in case that's helpful.

Cheers,
Sebastian

[bashOutput.txt](https://github.com/woodem/woo/files/5150567/bashOutput.txt)

**Comment by eudoxos** [comment]
Thanks for the log, that is helpful; I will try to reproduce the `OpenGL::OpenGL` issue locally and will get back.

**Comment by eudoxos** [comment]
The latest commit 94ad061 should fix this, please confirm (it should be `OpenGL::GL` instead).

**Comment by zipmo** [comment]
Thanks, this indeed fixed it. 
However, installation now fails due to a cmake ImportError:

ImportError: libQt5Core.so.5: cannot open shared object file: No such file or directory
    from PyQt5.QtCore import PYQT_VERSION_STR, QDir, QFile  

Full log is attached again.

Cheers,
Sebastian

[bashOutput1.txt](https://github.com/woodem/woo/files/5161341/bashOutput1.txt)

**Comment by eudoxos** [comment]
If you are under WSL1, you are probably hitting this bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895718 ; in that case use [this workaround](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895718#104) or switch to WSL2 .

**Comment by zipmo** [comment]
Thanks for the hint! I upgraded to WSL 2 and repeated the installation. It still gives me the ImportError on libQt5core. However, cmake runs up to 100 % and then raises an error: 

make: *** [Makefile:130: all] Error 2

Do you have any idea on this?

[bashOutput2.txt](https://github.com/woodem/woo/files/5166779/bashOutput2.txt)

**Comment by zipmo** [comment]
Thanks for the hint, switching to WSL 2 indeed solved the libQt5Core error. 
cmake building now works up to 100 %, but the installation fails with a cmake error:

CMake Error at cmake_install.cmake:245 (file):
  file INSTALL cannot find "/home/sebric/woo/gui/qt4/img_rc.py": No such file
  or directory.

Do yo have any idea on this?

Cheers,
Sebastian

[bashOutput2.txt](https://github.com/woodem/woo/files/5167286/bashOutput2.txt)

**Comment by eudoxos** [comment]
Fixed in the latest commit.

**Comment by zipmo** [comment]
Works! (Except for the GUI, but this is another thing) 
Thanks for your help!

**Comment by eudoxos** [comment]
Hi @zipmo, I think I tried to compile including the GUI in WSL2 with X11 (I forgot what it is called already) and everything was working (like the OpenGL view and the PyQt-based GUI). Please reopen if you hit some issues.
