### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by mboisson** [woodem/woo#32]
Hi,
Is there any plan to make releases of this project ? Installing from the git main branch is hardly reproducible. 

Thanks

**Comment by eudoxos** [comment]
I understand this is an inconvenience, it would be a good idea :) As workaround, you can install from a specific commit hash, that is reproducible.

**Comment by mboisson** [comment]
Commit are reproducibles, but there is no way to know whether they are stable, or which one should be preferred, etc.

**Comment by eudoxos** [comment]
OIC. I don't have resources for such broad quality assurance. I acknowledge the wish for release and understand the rationale (stability, compatibility) but will close the issue as it is too broad.

There are several things in this direction already:

* CI for every commit;
* programmatic is infrastructure to query API changes as described in https://woodem.org/api.html#changes , especially meant to cover the cases leading to silent behavior changes;
* support when resolving issues such as yours.

Beyond that, it would have to be contracted specifically. The license says:

https://github.com/woodem/woo/blob/476adb3953106f05f00c99a9e366f7369cd29f01/LICENSE#L258-L268
