### ISSUE TITLE
GLE can't be found

### ISSUE THREAD

**Issue by mboisson** [woodem/woo#36]
Hi,
Can you document what version of GLE is required by this ? 
```
        find_path(GLE_INCLUDE_DIR NAMES GL/gle.h PATHS /usr/include /usr/local/include)
        find_library(GLE_LIB NAMES gle)
        if(GLE_INCLUDE_DIR AND GLE_LIB)
                # create interface: https://foonathan.net/2016/07/cmake-dependency-handling/
                add_library(GLE INTERFACE)
                target_include_directories(GLE INTERFACE ${GLE_INCLUDE_DIR})
                target_link_libraries(GLE INTERFACE ${GLE_LIB})
        else()
                message(FATAL_ERROR "GLE library/headers not found.")
        endif()
``` 

I built GLE from source, from https://glx.sourceforge.io/
but it does not provide a `libgle.so`, nor any header files. Here is what it provides: 

```
[mboisson@build-node GLE]$ ls /home/mboisson/.local/easybuild/software/2020/avx2/Core/gle/4.2.5/*/
/home/mboisson/.local/easybuild/software/2020/avx2/Core/gle/4.2.5/bin/:
gle  glebtool  manip

/home/mboisson/.local/easybuild/software/2020/avx2/Core/gle/4.2.5/easybuild/:
avx2-Core-gle-4.2.5-easybuild-devel  easybuild-GLE-4.2.5-20210818.135740.log  easybuild-GLE-4.2.5-20210818.135740_test_report.md  GLE-4.2.5-c++14.patch  GLE-4.2.5.eb  reprod

/home/mboisson/.local/easybuild/software/2020/avx2/Core/gle/4.2.5/lib/:
libgle-graphics-4.2.5.so  pkgconfig

/home/mboisson/.local/easybuild/software/2020/avx2/Core/gle/4.2.5/lib64/:
libgle-graphics-4.2.5.so  pkgconfig

/home/mboisson/.local/easybuild/software/2020/avx2/Core/gle/4.2.5/share/:
doc  gle-graphics  man
``` 

Also, there is no `gle.h` file in the source directory of that package. 

So, what are `gle.h` and `libgle.so` supposed to be ?

**Comment by eudoxos** [comment]
GLE library is [GLE Tubing and Extrusions](https://sourceforge.net/projects/gle/), the one you link is something unrelated. Searching for `gle.h` in Debian repos found [the correct libgle3-dev](https://packages.debian.org/bullseye/libgle3-dev) package. If you are building for a cluster (as I assume), build witth `-DWOO_QT5=OFF` and you don't need any of the OpenGL things.

**Comment by eudoxos** [comment]
I added a brief explanation about `WOO_QT5` to the installation documentation (admittedly quite terse) [here](https://woodem.org/user/installation.html) plus 0cd6bcb6bdf7876c46ef057634aa4171d8731e19 added an explanation to CMakeLists

https://github.com/woodem/woo/blob/0cd6bcb6bdf7876c46ef057634aa4171d8731e19/CMakeLists.txt#L165

Closing; re-open if appropriate.
